config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created'
    else
      @movies_count = @list.movies.size
      @bookmarks = @list.bookmarks
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    @movies_count = @list.movies.size
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
  end

  private

  def list_params
    params.require(:list).permit(:name, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container my-3">
  <h1>Add a bookmark to <%= @list.name %>:</h1>

  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="d-flex">
        <%= link_to 'My Lists', lists_path, class: 'nav-link' %>
        <%= link_to 'New List', new_list_path, class: 'nav-link' %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center my-3">
  <h1>My Lists</h1>
  <%= link_to "New List", new_list_path, class: "custom-button" %>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
    <div class="col-4 my-3">
      <div class="category" style="background-image: url('<%= list.image %>');">
        <a class="category-name"><%= link_to list.name, list_path(list) %></a>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<div class="container my-5">
  <h1>Create List</h1>
  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :image %>
  <%= f.submit 'Create List', class: "submit" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.image %>)">
  <div class="banner-content">
    <%= @list.name %>
  </div>
  <div class="movies-counter">
    <p><%= @movies_count %> movies</p>
    </div>
</div>
<div class="container my-3">
  <div class="row">
    <div class="col-12 d-flex justify-content-end">
      <%= link_to 'Add a movie', new_list_bookmark_path(@list), class: 'custom-button' %>
    </div>
  </div>
</div>

<div class="container my-3">
  <div class="row">
    <% @bookmarks.each do |bookmark| %>
      <div class="col-4">
        <div class="card small-card">
          <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="Movie Poster Image">
          <div class="card-body">
            <div class="d-flex align-items-baseline justify-content-between">
              <h4 class="card-title"><%= bookmark.movie.title %></h4>
              <h6>⭐ <%= bookmark.movie.rating %></h6>
            </div>
            <p class="card-text"><%= bookmark.movie.overview %></p>
          </div>
            <footer class="blockquote-footer m-3"><%= bookmark.comment %></footer>
            <%= link_to "Delete", list_bookmark_path(@list, bookmark), data: { turbo_method: :delete }, class: "delete" %>
        </div>
      </div>
    <% end %>
  </div>

      <div class="container my-3">
        <div class="row">
          <div class="col-6 border my-3 py-3 px-5">
            <h1>Add a movie: </h1>
              <%= simple_form_for([@list, @bookmark]) do |f| %>
                <%= f.association :movie %>
                <%= f.input :comment %>
                <%= f.submit "Add movie", class: 'custom-button' %>
              <% end %>
          </div>
        </div>
      </div>
</div>